# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  This hands-on course takes the central topic of creativity and
  examines it from two different disciplines: Computer Science and Fine
  Art Printmaking. Students will use a range of processes, both digital
  and physical, to produce creative visual artwork. Students will also
  engage with big questions such as: What is creativity? How is
  creativity important to engaged citizenship? What does a ‘virtuous’
  society look like in terms of creating? How is creating both easier
  and more difficult in the digital age, and how does it intersect with
  authorship, copyright, and the open source/free culture movements?
baseurl: "/lbst150j" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: LBST 150 J
title: "The Engaged Citizen: The Art and Science of Creativity"
semester: Fall 2020

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - title: Course content
    subfolderitems:
      - page: Calendar
        url: '#calendar'
      - page: Projects
        url: '#projects'
      - page: Scale
        url: '#scale'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: yorgey
    name: Dr. Brent Yorgey
    email: yorgey@hendrix.edu
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me
  - id: gill
    name: Melissa Gill, M.A., M.F.A.
    email: gill@hendrix.edu
    web: http://www.melissagillart.com/
    phone: (501) 505-1562

offerings:
  - name: Section 1
    loc: online
    time: MWF 12:10pm - 1:00pm
    instructor: gill
  - name: Section 2
    loc: online
    time: MWF 12:10pm - 1:00pm
    instructor: yorgey

resources:
  - name: Recursive Drawing
    image: assets/images/rec-hearts.png
    url: http://recursivedrawing.com/
  - name: EscherSketch
    image: assets/images/eslogo2.svg
    url: https://eschersket.ch/
  - name: Context Free Art
    image: assets/images/fern.jpg
    url: https://www.contextfreeart.org/
  - name: William Kentridge
    image: assets/images/William_Kentridge_DSC_2685.jpg
    url: https://www.youtube.com/watch?v=SmaXqktW3A8&t=18s
  - name: James Taylor
    image: assets/images/taylor.png
    url: https://www.youtube.com/watch?v=14SOoTXqRys
  - name: Sol LeWitt
    image: assets/images/sol_lewitt.jpg
    url: https://massmoca.org/sol-lewitt/
  - name: Swoon
    image: assets/images/swoon.jpg
    url: https://www.youtube.com/watch?v=5298KZuW_JE
  - name: Ai Weiwei
    image: assets/images/surveillance.jpeg
    url: https://art21.org/watch/art-in-the-twenty-first-century/s6/ai-weiwei-in-change-segment/

extra-resources:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
